CrossReference: main.o Scanner.o Print.o Token.o
	g++  main.o Scanner.o Print.o Token.o -o CrossReference
Token.o: Token.cpp Token.h
	g++ -c Token.cpp
Scanner.o: Scanner.cpp Scanner.h
	g++ -c Scanner.cpp
Print.o: Print.cpp Print.h
	g++ -c Print.cpp
main.o: main.cpp common.h
	g++ -c main.cpp
clean:
	rm CrossReference Token.o Scanner.o Print.o main.o
